#variaveis
CFLAGS = -Wall #flag de complicação
LBLIBS = -lm   #bibliotecas a ligar

#exec: arquivos que geram o executavel
hello: organizar_codigo.c ./lib/cpx.c ./lib/cpx.h

#comando que chama o compilador com estes parametros
	gcc -Wall organizar_codigo.c ./lib/cpx.c -o hello

